name: yorktongunclub
favicon: null
layout_spectrum: 0.9679150215815753
typography_spectrum: 0.6445849952287972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6258715556468815
  lightness: 0.697687538806349
  saturation: 0.8375243949703872
  rhythmicContrast: 0.9993150418158621
purpose: []
